name: live2p-gpu
channels:
 - conda-forge
dependencies:
 - caiman
 - python
 - pip
 - websockets
 - websocket-client
 - pandas
 - seaborn
 - xarray
 - jupyterlab
 - notebook
 - tensorflow-gpu=2.0.0
 - opencv
 - pip:
   - scanimage-tiff-reader
   - pycuda
   - scikit-cuda